import { animation } from './effects/animation'
import { flex } from './layout/flex-box'
import typographyStyles from './fonts/font-styles'
import { gradients } from './color/gradients'
import { clamps } from './responsive/clamps'
import { margin } from './layout/margin'
import { colors } from './color/colors'
import globalStyles from './layout/global-style'
import { fonts } from './fonts/fonts'
import elements from './elements/element-styles'
export { animation, flex, typographyStyles, gradients, clamps, margin, colors, globalStyles, fonts, elements };